[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["cd site && npm install"]

[phases.build]
cmds = ["cd site && npx prisma generate && npm run build"]

[start]
cmd = "cd site && npm start"
